import {
    EVT_TICK_START,
    EVT_TICK_END,
    EVT_NODE_ENTER,
    EVT_NODE_OPEN,
    EVT_NODE_TICK,
    EVT_NODE_STATUS,
    EVT_NODE_CLOSE,
    EVT_NODE_EXIT,
    EVT_NODE_ABORT,
    EVT_NODE_LOG,
} from '../../constants.js';

export default [
    EVT_TICK_START,
    EVT_TICK_END,
    EVT_NODE_ENTER,
    EVT_NODE_OPEN,
    EVT_NODE_TICK,
    EVT_NODE_STATUS,
    EVT_NODE_CLOSE,
    EVT_NODE_EXIT,
    EVT_NODE_ABORT,
    EVT_NODE_LOG,
];
