module.exports = {
    // game objects
    'bbcodetextplugin': './plugins/bbcodetext-plugin.ts',
    'tagtextplugin': './plugins/tagtext-plugin.ts',
    'canvasplugin': './plugins/canvas-plugin.ts',
    'circlemaskimageplugin': './plugins/circlemaskimage-plugin.ts',
    'alphamaskimageplugin': './plugins/alphamaskimage-plugin.ts',
    'repeatimageplugin': './plugins/repeatimage-plugin.ts',
    'circularprogresscanvasplugin': './plugins/circularprogresscanvas-plugin.ts',
    'lineprogresscanvasplugin': './plugins/lineprogresscanvas-plugin.ts',
    'roundrectanglecanvasplugin': './plugins/roundrectanglecanvas-plugin.ts',
    'customprogresscanvasplugin': './plugins/customprogresscanvas-plugin.ts',
    'dynamictextplugin': './plugins/dynamictext-plugin.ts',
    'textplayerplugin': './plugins/textplayer-plugin.ts',
    'containerliteplugin': './plugins/containerlite-plugin.ts',
    'gridtableplugin': './plugins/gridtable-plugin.ts',
    'roundrectangleplugin': './plugins/roundrectangle-plugin.ts',
    'quadshapeplugin': './plugins/quadshape-plugin.ts',
    'lineshapeplugin': './plugins/lineshape-plugin.ts',
    'customshapesplugin': './plugins/customshapes-plugin.ts',
    'circularprogressplugin': './plugins/circularprogress-plugin.ts',
    'lineprogressplugin': './plugins/lineprogress-plugin.ts',
    'roundrectangleprogressplugin': './plugins/roundrectangleprogress-plugin.ts',
    'customprogressplugin': './plugins/customprogress-plugin.ts',
    'checkboxplugin': './plugins/checkbox-plugin.ts',
    'toggleswitchplugin': './plugins/toggleswitch-plugin.ts',
    'triangleplugin': './plugins/triangle-plugin.ts',
    'inputtextplugin': './plugins/inputtext-plugin.ts',
    'hiddeninputtextplugin': './plugins/hiddeninputtext-plugin.ts',
    'canvasinputplugin': './plugins/canvasinput-plugin.ts',
    'youtubeplayerplugin': './plugins/youtubeplayer-plugin.ts',
    'lineplugin': './plugins/line-plugin.ts',
    'ninepatchplugin': './plugins/ninepatch-plugin.ts',
    'ninepatch2plugin': './plugins/ninepatch2-plugin.ts',
    'meshplugin': './plugins/mesh-plugin.ts',
    'perspectiveimageplugin': './plugins/perspectiveimage-plugin.ts',
    'quadimageplugin': './plugins/quadimage-plugin.ts',
    'shatterimageplugin': './plugins/shatterimage-plugin.ts',
    'delaunayimageplugin': './plugins/delaunayimage-plugin.ts',
    'imageboxplugin': './plugins/imagebox-plugin.ts',
    'lazyloadimageboxplugin': './templates/lazyloadimagebox/lazyloadimagebox-plugin.ts',
    'transitionimageplugin': './plugins/transitionimage-plugin.ts',
    'transitionimagepackplugin': './templates/transitionimagepack/transitionimagepack-plugin.ts',
    'fullwindowrectangleplugin': './plugins/fullwindowrectangle-plugin.ts',
    'coverplugin': './plugins/cover-plugin.ts',
    'live2dplugin': ['./plugins/live2d-plugin.ts', true],
    'layermanagerplugin': './plugins/layermanager-plugin.ts',
    // texture
    'framemanagerplugin': './plugins/framemanager-plugin.ts',
    'canvasframemanagerplugin': './plugins/canvasframemanager-plugin.ts',
    'charactercacheplugin': './plugins/charactercache-plugin.ts',
    'clickboardtotextureplugin': './plugins/clickboardtotexture-plugin.ts',

    // custom file loader
    'awaitloaderplugin': './plugins/awaitloader-plugin.ts',
    'yamlloaderplugin': './plugins/yamlloader-plugin.ts',
    'webfontloaderplugin': './plugins/webfontloader-plugin.ts',    
    'scripttagloaderplugin': './plugins/scripttagloader-plugin.ts',
    'imageuriloaderplugin': './plugins/imageuriloader-plugin.ts',
    'loadinganimationsceneplugin': './plugins/loadinganimationscene-plugin.ts',
    'awaitcomlinkloaderplugin': './plugins/awaitcomlinkloader-plugin.ts',

    // actions
    'gridalignplugin': './plugins/gridalign-plugin.ts',
    'randomplaceplugin': './plugins/randomplace-plugin.ts',
    'gridcutimageplugin': './plugins/gridcutimage-plugin.ts',
    'cutjigsawimageplugin': './plugins/cutjigsawimage-plugin.ts',

    // input
    'dragplugin': './plugins/drag-plugin.ts',
    'dragspeedplugin': './plugins/dragspeed-plugin.ts',
    'sliderplugin': './plugins/slider-plugin.ts',
    'scrollerplugin': './plugins/scroller-plugin.ts',
    'buttonplugin': './plugins/button-plugin.ts',
    'clickoutsideplugin': './plugins/clickoutside-plugin.ts',
    'touchcursorplugin': './plugins/touchcursor-plugin.ts',
    'virtualjoystickplugin': './plugins/virtualjoystick-plugin.ts',
    'cursoratboundsplugin': './plugins/cursoratbounds-plugin.ts',
    'mousewheeltoupdownplugin': './plugins/mousewheeltoupdown-plugin.ts',
    'mousewheelscrollerplugin': './plugins/mousewheelscroller-plugin.ts',
    'pinchplugin': './plugins/pinch-plugin.ts',
    'dragrotateplugin': './plugins/dragrotate-plugin.ts',
    'gesturesplugin': './plugins/gestures-plugin.ts',
    'toucheventstopplugin': './plugins/toucheventstop-plugin.ts',
    'intouchingplugin': './plugins/intouching-plugin.ts',
    'touchhelperplugin': './plugins/touchhelper-plugin.ts',
    'touchstateplugin': './plugins/touchstate-plugin.ts',
    'keyshubplugin': './plugins/keyshub-plugin.ts',

    // member of game object
    'fadeplugin': './plugins/fade-plugin.ts',
    'scaleplugin': './plugins/scale-plugin.ts',
    'flipplugin': './plugins/flip-plugin.ts',
    'easemoveplugin': './plugins/easemove-plugin.ts',
    'easedataplugin': './plugins/easedata-plugin.ts',
    'pathfollowerplugin': './plugins/pathfollower-plugin.ts',
    'movetoplugin': './plugins/moveto-plugin.ts',
    'rotatetoplugin': './plugins/rotateto-plugin.ts',
    'rotateplugin': './plugins/rotate-plugin.ts',
    'flashplugin': './plugins/flash-plugin.ts',
    'tintrgbplugin': './plugins/tintrgb-plugin.ts',
    'polarcoordinateplugin': './plugins/polarcoordinate-plugin.ts',
    'viewportcoordinateplugin': './plugins/viewportcoordinate-plugin.ts',
    'effectpropertiesplugin': './plugins/effectproperties-plugin.ts',
    'shakepositionplugin': './plugins/shakeposition-plugin.ts',
    'interceptionplugin': './plugins/interception-plugin.ts',
    'anchorplugin': './plugins/anchor-plugin.ts',
    'boundsplugin': './plugins/bounds-plugin.ts',
    'stepplugin': './plugins/step-plugin.ts',
    'modalplugin': './plugins/modal-plugin.ts',
    'dropdownplugin': './plugins/dropdown-plugin.ts',
    'particlesalongboundsplugin': './plugins/particlesalongbounds-plugin.ts',
    'loadingprogressplugin': './plugins/loadingprogress-plugin.ts',
    // member of game object, arcade behavior
    'eightdirectionplugin': './plugins/eightdirection-plugin.ts',
    'bulletplugin': './plugins/bullet-plugin.ts',
    'shipplugin': './plugins/ship-plugin.ts',
    'buildarcadeobjectplugin': './plugins/buildarcadeobject-plugin.ts',

    // member of text
    'texttypingplugin': './plugins/texttyping-plugin.ts',
    'textpageplugin': './plugins/textpage-plugin.ts',
    'texteditplugin': './plugins/textedit-plugin.ts',
    'texttranslationplugin': './plugins/texttranslation-plugin.ts',
    'texttruncatorplugin': './plugins/texttruncator-plugin.ts',

    // extend of particles
    'bitmapzoneplugin': './plugins/bitmapzone-plugin.ts',
    'perlingrivatywellplugin': './plugins/perlingrivatywell-plugin.ts',

    // camera
    'scaleouterplugin': './plugins/scaleouter-plugin.ts',
    'cameracontrollerplugin': './plugins/cameracontroller-plugin.ts',

    // file input
    'filechooserplugin': './plugins/filechooser-plugin.ts',
    'filedropzoneplugin': './plugins/filedropzone-plugin.ts',

    // member of scene
    // sound
    'soundfadeplugin': './plugins/soundfade-plugin.ts',

    // control
    'runcommandsplugin': './plugins/runcommands-plugin.ts',
    'sequenceplugin': './plugins/sequence-plugin.ts',
    'fsmplugin': './plugins/fsm-plugin.ts',
    'statemanagerplugin': './plugins/statemanager-plugin.ts',
    'tcrpplugin': './plugins/tcrp-plugin.ts',
    'arcadetcrpplugin': './plugins/arcadetcrp-plugin.ts',
    'csvscenarioplugin': './plugins/csvscenario-plugin.ts',
    'csvscenariologic': './plugins/csvscenariologic.ts',
    'waiteventsplugin': './plugins/waitevents-plugin.ts',
    'eventpromiseplugin': './plugins/eventpromise-plugin.ts',
    'achievementsplugin': './plugins/achievements-plugin.ts',
    'ymlachievementsplugin': './plugins/ymlachievements-plugin.ts',
    'conditionstableplugin': './plugins/conditionstable-plugin.ts',
    'ymlconditionstableplugin': './plugins/ymlconditionstable-plugin.ts',
    'levelcounterplugin': './plugins/levelcounter-plugin.ts',
    'levelcounter': './plugins/levelcounter.ts',
    'datamonitorplugin': './plugins/datamonitor-plugin.ts',
    'datamonitor': './plugins/datamonitor.ts',
    'questplugin': './plugins/quest-plugin.ts',
    'loopinticksplugin': './plugins/loopinticks-plugin.ts',
    'groupnavigatorplugin': './plugins/groupnavigator-plugin.ts',
    'bracketparserplugin': './plugins/bracketparser-plugin.ts',
    'bracketparser2plugin': './plugins/bracketparser2-plugin.ts',
    'tagplayerplugin': './plugins/tagplayer-plugin.ts',
    'markedeventsheetsplugin': './plugins/markedeventsheets-plugin.ts',
    'yamleventsheetsplugin': './plugins/yamleventsheets-plugin.ts',

    // time
    'clockplugin': './plugins/clock-plugin.ts',
    'lifetimeplugin': './plugins/lifetime-plugin.ts',
    'awaytimeplugin': './plugins/awaytime-plugin.ts',
    'realtimetimersplugin': './plugins/realtimetimers-plugin.ts',

    // data structure
    'csvtoarrayplugin': './plugins/csvtoarray-plugin.ts',
    'csvtohashtableplugin': './plugins/csvtohashtable-plugin.ts',
    'restorabledataplugin': './plugins/restorabledata-plugin.ts',
    'buffdataplugin': './plugins/buffdata-plugin.ts',
    'canvasdataplugin': './plugins/canvasdata-plugin.ts',
    'uniqueitemlistplugin': './plugins/uniqueitemlist-plugin.ts',
    'pngappenderplugin': './plugins/pngappender-plugin.ts',

    // storage
    'localforagefilesplugin': './plugins/localforage-files-plugin.ts',
    'localstoragedataplugin': './plugins/localstorage-data-plugin.ts',

    // math
    'gashaponplugin': './plugins/gashapon-plugin.ts',
    'perlinplugin': './plugins/perlin-plugin.ts',
    'raycasterplugin': './plugins/raycaster-plugin.ts',
    'expressionparserplugin': './plugins/expressionparser-plugin.ts',
    'fuzzyplugin': './plugins/fuzzy-plugin.ts',
    'fuzzy': './plugins/fuzzy.ts',
    // geom
    'rhombusplugin': './plugins/rhombus-plugin.ts',
    'hexagonplugin': './plugins/hexagon-plugin.ts',
    // curve
    'spiralcurveplugin': './plugins/spiralcurve-plugin.ts',

    // string
    'xorplugin': './plugins/xor-plugin.ts',
    'lzstringplugin': './plugins/lzstring-plugin.ts',
    'stringtemplateplugin': './plugins/stringtemplate-plugin.ts',

    // shader
    'swirlfilterplugin': './plugins/swirlfilter-plugin.ts',
    'hsladjustfilterplugin': './plugins/hsladjustfilter-plugin.ts',
    'toonifyfilterplugin': './plugins/toonifyfilter-plugin.ts',
    'outlinefilterplugin': './plugins/outlinefilter-plugin.ts',
    'dissolvefilterplugin': './plugins/dissolvefilter-plugin.ts',
    'crossstitchingfilterplugin': './plugins/crossstitchingfilter-plugin.ts',
    'shockwavefilterplugin': './plugins/shockwavefilter-plugin.ts',
    'splitfilterplugin': './plugins/splitfilter-plugin.ts',
    'fisheyefilterplugin': './plugins/fisheyefilter-plugin.ts',
    'barrelfilterplugin': './plugins/barrelfilter-plugin.ts',
    'colorreplacefilterplugin': './plugins/colorreplacefilter-plugin.ts',
    'warpfilterplugin': './plugins/warpfilter-plugin.ts',
    'horrififilterplugin': './plugins/horrififilter-plugin.ts',
    'crtfilterplugin': './plugins/crtfilter-plugin.ts',
    'p3fxplugin': './plugins/p3fx-plugin.ts',

    // board
    'boardplugin': './plugins/board-plugin.ts',

    // graph
    'graphplugin': './plugins/graph-plugin.ts',

    // parse
    'parseplugin': './plugins/parse-plugin.ts',

    // firebase
    'firebaseplugin': './plugins/firebase-plugin.ts',

    // templates
    'bejeweled': './templates/bejeweled/Bejeweled.ts',
    'bejeweled2': './templates/bejeweled2/Bejeweled.ts',
    'uiplugin': './templates/ui/ui-plugin.ts',
    'dialogquest': './templates/dialog-quest/DialogQuest.ts',
    'spinnerplugin': './templates/spinner/spinner-plugin.ts',
    'gameobjectshellplugin': './templates/gameobjectshell/gameobjectshell-plugin.ts',

    // Plain class
    // rex ui
    'bbcodetext': './templates/ui/bbcodetext/BBCodeText.ts',
    'buttons': './templates/ui/buttons/Buttons.ts',
    'gridbuttons': './templates/ui/gridbuttons/GridButtons.ts',
    'fixwidthbuttons': './templates/ui/fixwidthbuttons/FixWidthButtons.ts',
    'fileselectorbutton': './templates/ui/fileselectorbutton/FileSelectorButton.ts',
    'canvas': './templates/ui/canvas/Canvas.ts',
    'circlemaskimage': './templates/ui/circlemaskimage/CircleMaskImage.ts',
    'alphamaskimage': './templates/ui/alphamaskimage/AlphaMaskImage.ts',
    'dynamictext': './templates/ui/dynamictext/DynamicText.ts',
    'textplayer': './templates/ui/textplayer/TextPlayer.ts',
    'circularprogress': './templates/ui/circularprogress/CircularProgress.ts',
    'circularprogresscanvas': './templates/ui/circularprogresscanvas/CircularProgressCanvas.ts',
    'lineprogress': './templates/ui/lineprogress/LineProgress.ts',
    'roundrectangleprogress': './templates/ui/roundrectangleprogress/RoundRectangleProgress.ts',
    'lineprogresscanvas': './templates/ui/lineprogresscanvas/LineProgressCanvas.ts',
    'knob': './templates/ui/knob/Knob.ts',
    'customshapes': './templates/ui/customshapes/CustomShapes.ts',
    'customprogress': './templates/ui/customprogress/CustomProgress.ts',
    'colorcomponents': './templates/ui/colorinput/colorcomponents/ColorComponents.ts',
    'checkbox': './templates/ui/checkbox/Checkbox.ts',
    'toggleswitch': './templates/ui/toggleswitch/ToggleSwitch.ts',
    'triangle': './templates/ui/triangle/Triangle.ts',
    'colorinput': './templates/ui/colorinput/colorinput/ColorInput.ts',
    'colorpicker': './templates/ui/colorinput/colorpicker/ColorPicker.ts',
    'filechooser': './templates/ui/filechooser/FileChooser.ts',
    'filedropzone': './templates/ui/filedropzone/FileDropZone.ts',
    'chart': './templates/ui/chart/Chart.ts',
    'dialog': './templates/ui/dialog/Dialog.ts',
    'confirmdialog': './templates/ui/confirmdialog/ConfirmDialog.ts',
    'nameinputdialog': './templates/ui/nameinputdialog/NameInputDialog.ts',
    'fixwidthsizer': './templates/ui/fixwidthsizer/FixWidthSizer.ts',
    'overlapsizer': './templates/ui/overlapsizer/OverlapSizer.ts',
    'flip': './templates/ui/flip/Flip.ts',
    'gridsizer': './templates/ui/gridsizer/GridSizer.ts',
    'gridtable': './templates/ui/gridtable/GridTable.ts',
    'label': './templates/ui/label/Label.ts',
    'simplelabel': './templates/ui/simplelabel/SimpleLabel.ts',
    'titlelabel': './templates/ui/titlelabel/TitleLabel.ts',
    'namevaluelabel': './templates/ui/namevaluelabel/NameValueLabel.ts',
    'expbar': './templates/ui/expbar/ExpBar.ts',
    'menu': './templates/ui/menu/Menu.ts',
    'dropdownlist': './templates/ui/dropdownlist/DropDownList.ts',
    'simpledropdownlist': './templates/ui/simpledropdownlist/SimpleDropDownList.ts',
    'ninepatch': './templates/ui/ninepatch/NinePatch.ts',
    'badgelabel': './templates/ui/badgelabel/BadgeLabel.ts',
    'pages': './templates/ui/pages/Pages.ts',
    'perspectivecard': './templates/ui/perspectivecard/PerspectiveCard.ts',
    'tabpages': './templates/ui/tabpages/TabPages.ts',
    'holygrail': './templates/ui/holygrail/HolyGrail.ts',
    'pan': './templates/ui/pan/Pan.ts',
    'pinch': './templates/ui/pinch/Pinch.ts',
    'press': './templates/ui/press/Press.ts',
    'rotate': './templates/ui/rotate/Rotate.ts',
    'roundrectangle': './templates/ui/roundrectangle/RoundRectangle.ts',
    'statesroundrectangle': './templates/ui/statesroundrectangle/StatesRoundRectangle.ts',
    'roundrectanglecanvas': './templates/ui/roundrectanglecanvas/RoundRectangleCanvas.ts',
    'scrollablepanel': './templates/ui/scrollablepanel/ScrollablePanel.ts',
    'sizer': './templates/ui/sizer/Sizer.ts',
    'slider': './templates/ui/slider/Slider.ts',
    'numberbar': './templates/ui/numberbar/NumberBar.ts',
    'scrollbar': './templates/ui/scrollbar/ScrollBar.ts',
    'swipe': './templates/ui/swipe/Swipe.ts',
    'tabs': './templates/ui/tabs/Tabs.ts',
    'tagtext': './templates/ui/tagtext/TagText.ts',
    'tap': './templates/ui/tap/Tap.ts',
    'textarea': './templates/ui/textarea/TextArea.ts',
    'textareainput': './templates/ui/textareainput/TextAreaInput.ts',
    'textbox': './templates/ui/textbox/TextBox.ts',
    'toast': './templates/ui/toast/Toast.ts',
    'folder': './templates/ui/folder/Folder.ts',
    'trees': './templates/ui/trees/Trees.ts',
    'tweaker': './templates/ui/tweaker/Tweaker.ts',
    'splitpanels': './templates/ui/splitpanels/SplitPanels.ts',
    'sides': './templates/ui/sides/Sides.ts',

    // spinner
    'aiospinner': './templates/spinner/aio/AIO.ts',
    'arrowspinner': './templates/spinner/arrow/Arrow.ts',
    'audiospinner': './templates/spinner/audio/Audio.ts',
    'ballspinner': './templates/spinner/ball/Ball.ts',
    'barsspinner': './templates/spinner/bars/Bars.ts',
    'boxspinner': './templates/spinner/box/Box.ts',
    'clockspinner': './templates/spinner/clock/Clock.ts',
    'cubespinner': './templates/spinner/cube/Cube.ts',
    'customspinner': './templates/spinner/custom/Custom.ts',
    'dotsspinner': './templates/spinner/dots/Dots.ts',
    'facebookspinner': './templates/spinner/facebook/Facebook.ts',
    'gridspinner': './templates/spinner/grid/Grid.ts',
    'heartsspinner': './templates/spinner/hearts/Hearts.ts',
    'iosspinner': './templates/spinner/ios/Ios.ts',
    'orbitspinner': './templates/spinner/orbit/Orbit.ts',
    'ovalspinner': './templates/spinner/oval/Oval.ts',
    'puffspinner': './templates/spinner/puff/Puff.ts',
    'radiospinner': './templates/spinner/radio/Radio.ts',
    'ringsspinner': './templates/spinner/rings/Rings.ts',
    'spinner': './templates/spinner/spinner/Spinner.ts',

    // scenario
    'mdscenario': './templates/scenario/mdscenario/MDScenario.ts',
    'mdscenarioplugin': './templates/scenario/mdscenario/mdscenario-plugin.ts',
    'jsonscenario': './templates/scenario/jsonscenario/JSONScenario.ts',
    'jsonscenarioplugin': './templates/scenario/jsonscenario/jsonscenario-plugin.ts',
    'yamlscenario': './templates/scenario/yamlscenario/YAMLScenario.ts',
    'yamlscenarioplugin': './templates/scenario/yamlscenario/yamlscenario-plugin.ts',

    // network
    'firebase': './plugins/firebase.ts',
    'parse': './plugins/parse.ts',

    // other
    'bbcodelog': './plugins/bbcodelog.ts',
}