module.exports = {
    // game objects
    'bbcodetextplugin': './plugins/bbcodetext-plugin.js',
    'tagtextplugin': './plugins/tagtext-plugin.js',
    'canvasplugin': './plugins/canvas-plugin.js',
    'circlemaskimageplugin': './plugins/circlemaskimage-plugin.js',
    'alphamaskimageplugin': './plugins/alphamaskimage-plugin.js',
    'circularprogresscanvasplugin': './plugins/circularprogresscanvas-plugin.js',
    'lineprogresscanvasplugin': './plugins/lineprogresscanvas-plugin.js',
    'roundrectanglecanvasplugin': './plugins/roundrectanglecanvas-plugin.js',
    'dynamictextplugin': './plugins/dynamictext-plugin.js',
    'textplayerplugin': './plugins/textplayer-plugin.js',
    'containerliteplugin': './plugins/containerlite-plugin.js',
    'gridtableplugin': './plugins/gridtable-plugin.js',
    'roundrectangleplugin': './plugins/roundrectangle-plugin.js',
    'customshapesplugin': './plugins/customshapes-plugin.js',
    'circularprogressplugin': './plugins/circularprogress-plugin.js',
    'lineprogressplugin': './plugins/lineprogress-plugin.js',
    'customprogressplugin': './plugins/customprogress-plugin.js',
    'checkboxplugin': './plugins/checkbox-plugin.js',
    'toggleswitchplugin': './plugins/toggleswitch-plugin.js',
    'triangleplugin': './plugins/triangle-plugin.js',
    'inputtextplugin': './plugins/inputtext-plugin.js',
    'hiddeninputtextplugin': './plugins/hiddeninputtext-plugin.js',
    'canvasinputplugin': './plugins/canvasinput-plugin.js',
    'youtubeplayerplugin': './plugins/youtubeplayer-plugin.js',
    'lineplugin': './plugins/line-plugin.js',
    'ninepatchplugin': './plugins/ninepatch-plugin.js',
    'ninepatch2plugin': './plugins/ninepatch2-plugin.js',
    'perspectiveimageplugin': './plugins/perspectiveimage-plugin.js',
    'quadimageplugin': './plugins/quadimage-plugin.js',
    'shatterimageplugin': './plugins/shatterimage-plugin.js',
    'imageboxplugin': './plugins/imagebox-plugin.js',
    'transitionimageplugin': './plugins/transitionimage-plugin.js',
    'transitionimagepackplugin': './templates/transitionimagepack/transitionimagepack-plugin.js',
    'fullwindowrectangleplugin': './plugins/fullwindowrectangle-plugin.js',
    'coverplugin': './plugins/cover-plugin.js',
    'live2dplugin': ['./plugins/live2d-plugin.js', true],
    'layermanagerplugin': './plugins/layermanager-plugin.js',
    // texture
    'framemanagerplugin': './plugins/framemanager-plugin.js',
    'canvasframemanagerplugin': './plugins/canvasframemanager-plugin.js',
    'charactercacheplugin': './plugins/charactercache-plugin.js',
    // effect layer (shader)
    'effectlayerplugin': './plugins/effectlayer-plugin.js',
    'outlineeffectlayerplugin': './plugins/outlineeffectlayer-plugin.js',

    // custom file loader
    'webfontloaderplugin': './plugins/webfontloader-plugin.js',
    'awaitloaderplugin': './plugins/awaitloader-plugin.js',
    'scripttagloaderplugin': './plugins/scripttagloader-plugin.js',
    'imageuriloaderplugin': './plugins/imageuriloader-plugin.js',

    // actions
    'gridalignplugin': './plugins/gridalign-plugin.js',
    'randomplaceplugin': './plugins/randomplace-plugin.js',
    'gridcutimageplugin': './plugins/gridcutimage-plugin.js',
    'cutjigsawimageplugin': './plugins/cutjigsawimage-plugin.js',

    // input
    'dragplugin': './plugins/drag-plugin.js',
    'dragspeedplugin': './plugins/dragspeed-plugin.js',
    'sliderplugin': './plugins/slider-plugin.js',
    'scrollerplugin': './plugins/scroller-plugin.js',
    'buttonplugin': './plugins/button-plugin.js',
    'clickoutsideplugin': './plugins/clickoutside-plugin.js',
    'touchcursorplugin': './plugins/touchcursor-plugin.js',
    'virtualjoystickplugin': './plugins/virtualjoystick-plugin.js',
    'cursoratboundplugin': './plugins/cursoratbound-plugin.js',
    'mousewheeltoupdownplugin': './plugins/mousewheeltoupdown-plugin.js',
    'mousewheelscrollerplugin': './plugins/mousewheelscroller-plugin.js',
    'pinchplugin': './plugins/pinch-plugin.js',
    'dragrotateplugin': './plugins/dragrotate-plugin.js',
    'gesturesplugin': './plugins/gestures-plugin.js',
    'toucheventstopplugin': './plugins/toucheventstop-plugin.js',
    'intouchingplugin': './plugins/intouching-plugin.js',
    'touchhelperplugin': './plugins/touchhelper-plugin.js',
    'touchstateplugin': './plugins/touchstate-plugin.js',
    'keyshubplugin': './plugins/keyshub-plugin.js',

    // member of game object
    'fadeplugin': './plugins/fade-plugin.js',
    'scaleplugin': './plugins/scale-plugin.js',
    'flipplugin': './plugins/flip-plugin.js',
    'easemoveplugin': './plugins/easemove-plugin.js',
    'easedataplugin': './plugins/easedata-plugin.js',
    'pathfollowerplugin': './plugins/pathfollower-plugin.js',
    'movetoplugin': './plugins/moveto-plugin.js',
    'rotatetoplugin': './plugins/rotateto-plugin.js',
    'rotateplugin': './plugins/rotate-plugin.js',
    'flashplugin': './plugins/flash-plugin.js',
    'tintrgbplugin': './plugins/tintrgb-plugin.js',
    'polarcoordinateplugin': './plugins/polarcoordinate-plugin.js',
    'viewportcoordinateplugin': './plugins/viewportcoordinate-plugin.js',
    'effectpropertiesplugin': './plugins/effectproperties-plugin.js',
    'shakepositionplugin': './plugins/shakeposition-plugin.js',
    'interceptionplugin': './plugins/interception-plugin.js',
    'anchorplugin': './plugins/anchor-plugin.js',
    'boundsplugin': './plugins/bounds-plugin.js',
    'stepplugin': './plugins/step-plugin.js',
    'modalplugin': './plugins/modal-plugin.js',
    'dropdownplugin': './plugins/dropdown-plugin.js',
    'particlesalongboundsplugin': './plugins/particlesalongbounds-plugin.js',
    'loadingprogressplugin': './plugins/loadingprogress-plugin.js',
    // member of game object, arcade behavior
    'eightdirectionplugin': './plugins/eightdirection-plugin.js',
    'bulletplugin': './plugins/bullet-plugin.js',
    'shipplugin': './plugins/ship-plugin.js',
    'buildarcadeobjectplugin': './plugins/buildarcadeobject-plugin.js',

    // member of text
    'texttypingplugin': './plugins/texttyping-plugin.js',
    'textpageplugin': './plugins/textpage-plugin.js',
    'texteditplugin': './plugins/textedit-plugin.js',
    'texttranslationplugin': './plugins/texttranslation-plugin.js',

    // extend of particles
    'bitmapzoneplugin': './plugins/bitmapzone-plugin.js',
    'perlingrivatywellplugin': './plugins/perlingrivatywell-plugin.js',

    // camera
    'scaleouterplugin': './plugins/scaleouter-plugin.js',

    // file input
    'filechooserplugin': './plugins/filechooser-plugin.js',
    'filedropzoneplugin': './plugins/filedropzone-plugin.js',

    // member of scene
    // sound
    'soundfadeplugin': './plugins/soundfade-plugin.js',

    // control
    'runcommandsplugin': './plugins/runcommands-plugin.js',
    'sequenceplugin': './plugins/sequence-plugin.js',
    'fsmplugin': './plugins/fsm-plugin.js',
    'statemanagerplugin': './plugins/statemanager-plugin.js',
    'tcrpplugin': './plugins/tcrp-plugin.js',
    'arcadetcrpplugin': './plugins/arcadetcrp-plugin.js',
    'csvscenarioplugin': './plugins/csvscenario-plugin.js',
    'waiteventsplugin': './plugins/waitevents-plugin.js',
    'eventpromiseplugin': './plugins/eventpromise-plugin.js',
    'achievementsplugin': './plugins/achievements-plugin.js',
    'ymlachievementsplugin': './plugins/ymlachievements-plugin.js',
    'conditionstableplugin': './plugins/conditionstable-plugin.js',
    'ymlconditionstableplugin': './plugins/ymlconditionstable-plugin.js',
    'levelcounterplugin': './plugins/levelcounter-plugin.js',
    'levelcounter': './plugins/levelcounter.js',
    'questplugin': './plugins/quest-plugin.js',
    'loopinticksplugin': './plugins/loopinticks-plugin.js',
    'bracketparserplugin': './plugins/bracketparser-plugin.js',
    'bracketparser2plugin': './plugins/bracketparser2-plugin.js',
    'tagplayerplugin': './plugins/tagplayer-plugin.js',
    'markedeventsheetsplugin': './plugins/markedeventsheets-plugin.js',

    // time
    'clockplugin': './plugins/clock-plugin.js',
    'lifetimeplugin': './plugins/lifetime-plugin.js',
    'awaytimeplugin': './plugins/awaytime-plugin.js',
    'realtimetimersplugin': './plugins/realtimetimers-plugin.js',

    // data structure
    'csvtoarrayplugin': './plugins/csvtoarray-plugin.js',
    'csvtohashtableplugin': './plugins/csvtohashtable-plugin.js',
    'restorabledataplugin': './plugins/restorabledata-plugin.js',
    'buffdataplugin': './plugins/buffdata-plugin.js',
    'canvasdataplugin': './plugins/canvasdata-plugin.js',
    'uniqueitemlistplugin': './plugins/uniqueitemlist-plugin.js',
    'pngappenderplugin': './plugins/pngappender-plugin.js',

    // storage
    'localforagefilesplugin': './plugins/localforage-files-plugin.js',
    'localstoragedataplugin': './plugins/localstorage-data-plugin.js',

    // math
    'gashaponplugin': './plugins/gashapon-plugin.js',
    'perlinplugin': './plugins/perlin-plugin.js',
    'raycasterplugin': './plugins/raycaster-plugin.js',
    'expressionparserplugin': './plugins/expressionparser-plugin.js',
    'fuzzyplugin': './plugins/fuzzy-plugin.js',
    'fuzzy': './plugins/fuzzy.js',
    // geom
    'rhombusplugin': './plugins/rhombus-plugin.js',
    'hexagonplugin': './plugins/hexagon-plugin.js',
    // curve
    'spiralcurveplugin': './plugins/spiralcurve-plugin.js',

    // string
    'xorplugin': './plugins/xor-plugin.js',
    'lzstringplugin': './plugins/lzstring-plugin.js',
    'stringtemplateplugin': './plugins/stringtemplate-plugin.js',

    // shader
    'swirlpipelineplugin': './plugins/swirlpipeline-plugin.js',
    'pixelationpipelineplugin': './plugins/pixelationpipeline-plugin.js',
    'grayscalepipelineplugin': './plugins/grayscalepipeline-plugin.js',
    'inversepipelineplugin': './plugins/inversepipeline-plugin.js',
    'hsladjustpipelineplugin': './plugins/hsladjustpipeline-plugin.js',
    'glowfilterpipelineplugin': './plugins/glowfilterpipeline-plugin.js',
    'toonifypipelineplugin': './plugins/toonifypipeline-plugin.js',
    'outlinepipelineplugin': './plugins/outlinepipeline-plugin.js',
    'dissolvepipelineplugin': './plugins/dissolvepipeline-plugin.js',
    'crossstitchingpipelineplugin': './plugins/crossstitchingpipeline-plugin.js',
    'shockwavepipelineplugin': './plugins/shockwavepipeline-plugin.js',
    'splitpipelineplugin': './plugins/splitpipeline-plugin.js',
    'fisheyepipelineplugin': './plugins/fisheyepipeline-plugin.js',
    'barrelpipelineplugin': './plugins/barrelpipeline-plugin.js',
    'glowfilter2pipelineplugin': './plugins/glowfilter2pipeline-plugin.js',
    'colorreplacepipelineplugin': './plugins/colorreplacepipeline-plugin.js',
    'kawaseblurpipelineplugin': './plugins/kawaseblurpipeline-plugin.js',
    'dropshadowpipelineplugin': './plugins/dropshadowpipeline-plugin.js',
    'warppipelineplugin': './plugins/warppipeline-plugin.js',
    'horrifipipelineplugin': './plugins/horrifipipeline-plugin.js',

    'localmaskplugin': './plugins/localmask-plugin.js',

    // board
    'boardplugin': './plugins/board-plugin.js',

    // graph
    'graphplugin': './plugins/graph-plugin.js',

    // parse
    'parseplugin': './plugins/parse-plugin.js',

    // firebase
    'firebaseplugin': './plugins/firebase-plugin.js',

    // templates
    'bejeweled': './templates/bejeweled/Bejeweled.js',
    'uiplugin': './templates/ui/ui-plugin.js',
    'dialogquest': './templates/dialog-quest/DialogQuest.js',
    'spinnerplugin': './templates/spinner/spinner-plugin.js',
    'gameobjectshellplugin': './templates/gameobjectshell/gameobjectshell-plugin.js',

    // Plain class
    // rex ui
    'bbcodetext': './templates/ui/bbcodetext/BBCodeText.js',
    'buttons': './templates/ui/buttons/Buttons.js',
    'gridbuttons': './templates/ui/gridbuttons/GridButtons.js',
    'fixwidthbuttons': './templates/ui/fixwidthbuttons/FixWidthButtons.js',
    'fileselectorbutton': './templates/ui/fileselectorbutton/FileSelectorButton.js',
    'canvas': './templates/ui/canvas/Canvas.js',
    'circlemaskimage': './templates/ui/circlemaskimage/CircleMaskImage.js',
    'alphamaskimage': './templates/ui/alphamaskimage/AlphaMaskImage.js',
    'dynamictext': './templates/ui/dynamictext/DynamicText.js',
    'textplayer': './templates/ui/textplayer/TextPlayer.js',
    'circularprogress': './templates/ui/circularprogress/CircularProgress.js',
    'circularprogresscanvas': './templates/ui/circularprogresscanvas/CircularProgressCanvas.js',
    'lineprogress': './templates/ui/lineprogress/LineProgress.js',
    'lineprogresscanvas': './templates/ui/lineprogresscanvas/LineProgressCanvas.js',
    'knob': './templates/ui/knob/Knob.js',
    'customshapes': './templates/ui/customshapes/CustomShapes.js',
    'customprogress': './templates/ui/customprogress/CustomProgress.js',
    'colorcomponents': './templates/ui/colorinput/colorcomponents/ColorComponents.js',
    'checkbox': './templates/ui/checkbox/Checkbox.js',
    'toggleswitch': './templates/ui/toggleswitch/ToggleSwitch.js',
    'triangle': './templates/ui/triangle/Triangle.js',
    'colorinput': './templates/ui/colorinput/colorinput/ColorInput.js',
    'colorpicker': './templates/ui/colorinput/colorpicker/ColorPicker.js',
    'filechooser': './templates/ui/filechooser/FileChooser.js',
    'filedropzone': './templates/ui/filedropzone/FileDropZone.js',
    'chart': './templates/ui/chart/Chart.js',
    'dialog': './templates/ui/dialog/Dialog.js',
    'confirmdialog': './templates/ui/confirmdialog/ConfirmDialog.js',
    'fixwidthsizer': './templates/ui/fixwidthsizer/FixWidthSizer.js',
    'overlapsizer': './templates/ui/overlapsizer/OverlapSizer.js',
    'flip': './templates/ui/flip/Flip.js',
    'gridsizer': './templates/ui/gridsizer/GridSizer.js',
    'gridtable': './templates/ui/gridtable/GridTable.js',
    'label': './templates/ui/label/Label.js',
    'simplelabel': './templates/ui/simplelabel/SimpleLabel.js',
    'titlelabel': './templates/ui/titlelabel/TitleLabel.js',
    'namevaluelabel': './templates/ui/namevaluelabel/NameValueLabel.js',
    'menu': './templates/ui/menu/Menu.js',
    'dropdownlist': './templates/ui/dropdownlist/DropDownList.js',
    'simpledropdownlist': './templates/ui/simpledropdownlist/SimpleDropDownList.js',
    'ninepatch': './templates/ui/ninepatch/NinePatch.js',
    'badgelabel': './templates/ui/badgelabel/BadgeLabel.js',
    'pages': './templates/ui/pages/Pages.js',
    'perspectivecard': './templates/ui/perspectivecard/PerspectiveCard.js',
    'tabpages': './templates/ui/tabpages/TabPages.js',
    'holygrail': './templates/ui/holygrail/HolyGrail.js',
    'pan': './templates/ui/pan/Pan.js',
    'pinch': './templates/ui/pinch/Pinch.js',
    'press': './templates/ui/press/Press.js',
    'rotate': './templates/ui/rotate/Rotate.js',
    'roundrectangle': './templates/ui/roundrectangle/RoundRectangle.js',
    'statesroundrectangle': './templates/ui/statesroundrectangle/StatesRoundRectangle.js',
    'roundrectanglecanvas': './templates/ui/roundrectanglecanvas/RoundRectangleCanvas.js',
    'scrollablepanel': './templates/ui/scrollablepanel/ScrollablePanel.js',
    'sizer': './templates/ui/sizer/Sizer.js',
    'slider': './templates/ui/slider/Slider.js',
    'numberbar': './templates/ui/numberbar/NumberBar.js',
    'scrollbar': './templates/ui/scrollbar/ScrollBar.js',
    'swipe': './templates/ui/swipe/Swipe.js',
    'tabs': './templates/ui/tabs/Tabs.js',
    'tagtext': './templates/ui/tagtext/TagText.js',
    'tap': './templates/ui/tap/Tap.js',
    'textarea': './templates/ui/textarea/TextArea.js',
    'textareainput': './templates/ui/textareainput/TextAreaInput.js',
    'textbox': './templates/ui/textbox/TextBox.js',
    'toast': './templates/ui/toast/Toast.js',
    'tweaker': './templates/ui/tweaker/Tweaker.js',
    'sides': './templates/ui/sides/Sides.js',
    'uimaker': './templates/ui/maker/Maker.js',

    // spinner
    'audiospinner': './templates/spinner/audio/Audio.js',
    'ballspinner': './templates/spinner/ball/Ball.js',
    'barsspinner': './templates/spinner/bars/Bars.js',
    'boxspinner': './templates/spinner/box/Box.js',
    'clockspinner': './templates/spinner/clock/Clock.js',
    'cubespinner': './templates/spinner/cube/Cube.js',
    'customspinner': './templates/spinner/custom/Custom.js',
    'dotsspinner': './templates/spinner/dots/Dots.js',
    'facebookspinner': './templates/spinner/facebook/Facebook.js',
    'gridspinner': './templates/spinner/grid/Grid.js',
    'losspinner': './templates/spinner/los/Los.js',
    'orbitspinner': './templates/spinner/orbit/Orbit.js',
    'ovalspinner': './templates/spinner/oval/Oval.js',
    'puffspinner': './templates/spinner/puff/Puff.js',
    'radiospinner': './templates/spinner/radio/Radio.js',
    'ringsspinner': './templates/spinner/rings/Rings.js',
    'spinner': './templates/spinner/spinner/Spinner.js',
    // others
    'firebase': './plugins/firebase.js',
    'parse': './plugins/parse.js'
}