import {
    EVT_GROUP_START,
    EVT_GROUP_CONTINUE,
    EVT_GROUP_COMPLETE,
    EVT_GROUP_STOP,
    EVT_EVENTSHEET_ADD,
    EVT_EVENTSHEET_REMOVE,
    EVT_EVENTSHEET_REMOVE_ALL,
    EVT_EVENTSHEET_OPEN,
    EVT_EVENTSHEET_CONDITION,
    EVT_EVENTSHEET_ENTER,
    EVT_EVENTSHEET_CATCH,
    EVT_EVENTSHEET_TICK,
    EVT_EVENTSHEET_STATUS,
    EVT_EVENTSHEET_CLOSE,
    EVT_EVENTSHEET_EXIT,
    EVT_EVENTSHEET_SKIP,
    EVT_EVENTSHEET_ABORT,
    EVT_EVENTSHEET_ROUND_BREAK,
    EVT_LABEL_ENTER,
    EVT_LABEL_EXIT,
    EVT_COMMAND_START,
    EVT_COMMAND_END,
    EVT_COMMAND_PAUSE,
    EVT_COMMAND_RESUME,
    EVT_COMMAND_ABORT,
    EVT_CONDITION_EVAL,
    EVT_REPEAT_ITERATION,
    EVT_PAUSE_CLICK,
    EVT_PAUSE_KEY,
    EVT_PAUSE_INPUT,
    EVT_RESUME_INPUT,
} from '../../eventsheetmanager/constants.js';

var CreateHandlers = function (recorder) {
    return {
        [EVT_GROUP_START]: recorder.onGroupStart,
        [EVT_GROUP_CONTINUE]: recorder.onGroupContinue,
        [EVT_GROUP_COMPLETE]: recorder.onGroupComplete,
        [EVT_GROUP_STOP]: recorder.onGroupStop,
        [EVT_EVENTSHEET_ADD]: recorder.onEventSheetAdd,
        [EVT_EVENTSHEET_REMOVE]: recorder.onEventSheetRemove,
        [EVT_EVENTSHEET_REMOVE_ALL]: recorder.onEventSheetRemoveAll,
        [EVT_EVENTSHEET_OPEN]: recorder.onEventSheetOpen,
        [EVT_EVENTSHEET_CONDITION]: recorder.onEventSheetCondition,
        [EVT_EVENTSHEET_ENTER]: recorder.onEventSheetEnter,
        [EVT_EVENTSHEET_CATCH]: recorder.onEventSheetCatch,
        [EVT_EVENTSHEET_TICK]: recorder.onEventSheetTick,
        [EVT_EVENTSHEET_STATUS]: recorder.onEventSheetStatus,
        [EVT_EVENTSHEET_CLOSE]: recorder.onEventSheetClose,
        [EVT_EVENTSHEET_EXIT]: recorder.onEventSheetExit,
        [EVT_EVENTSHEET_SKIP]: recorder.onEventSheetSkip,
        [EVT_EVENTSHEET_ABORT]: recorder.onEventSheetAbort,
        [EVT_EVENTSHEET_ROUND_BREAK]: recorder.onEventSheetRoundBreak,
        [EVT_LABEL_ENTER]: recorder.onLabelEnter,
        [EVT_LABEL_EXIT]: recorder.onLabelExit,
        [EVT_COMMAND_START]: recorder.onCommandStart,
        [EVT_COMMAND_END]: recorder.onCommandEnd,
        [EVT_COMMAND_PAUSE]: recorder.onCommandPause,
        [EVT_COMMAND_RESUME]: recorder.onCommandResume,
        [EVT_COMMAND_ABORT]: recorder.onCommandAbort,
        [EVT_CONDITION_EVAL]: recorder.onConditionEval,
        [EVT_REPEAT_ITERATION]: recorder.onRepeatIteration,
        [EVT_PAUSE_CLICK]: recorder.onPauseClick,
        [EVT_PAUSE_KEY]: recorder.onPauseKey,
        [EVT_PAUSE_INPUT]: recorder.onPauseInput,
        [EVT_RESUME_INPUT]: recorder.onResumeInput,
    };
}

export default CreateHandlers;
