import AddEffectProperties from './behaviors/effectproperties/AddEffectProperties.js';
export default AddEffectProperties;

import {
    AddBarrelProperties,
    AddBlackWhiteProperties,
    AddBlurProperties,
    AddBokehProperties,
    AddBrightnessProperties,
    AddBrownProperties,
    AddContrastProperties,
    AddDesaturateProperties,
    AddDesaturateLuminanceProperties,
    AddDisplacementProperties,
    AddGlowProperties,
    AddGrayscaleProperties,
    AddHueProperties,
    AddKodachromeProperties,
    AddLSDProperties,
    AddNegativeProperties,
    AddPixelateProperties,
    AddPolaroidProperties,
    AddSaturateProperties,
    AddSepiaProperties,
    AddShadowProperties,
    AddShiftToBGRProperties,
    AddTechnicolorProperties,
    AddTiltShiftProperties,
    AddVintagePinholeProperties,
} from './behaviors/effectproperties/EffectProperties.js';

export {
    AddBarrelProperties,
    AddBlackWhiteProperties,
    AddBlurProperties,
    AddBokehProperties,
    AddBrightnessProperties,
    AddBrownProperties,
    AddContrastProperties,
    AddDesaturateProperties,
    AddDesaturateLuminanceProperties,
    AddDisplacementProperties,
    AddGlowProperties,
    AddGrayscaleProperties,
    AddHueProperties,
    AddKodachromeProperties,
    AddLSDProperties,
    AddNegativeProperties,
    AddPixelateProperties,
    AddPolaroidProperties,
    AddSaturateProperties,
    AddSepiaProperties,
    AddShadowProperties,
    AddShiftToBGRProperties,
    AddTechnicolorProperties,
    AddTiltShiftProperties,
    AddVintagePinholeProperties,
}